### ISSUE TITLE
Wrong array key in 'Split Message By Array' action

### ISSUE THREAD

**Issue by ElBabbler** [elasticio/splitter-component#24]
Searching for key `res` instead of set `result`

Configure input:
![image](https://user-images.githubusercontent.com/22715422/67486065-f266b500-f673-11e9-89aa-ee194cf8e977.png)

Input data structure:
```
{
  "result": [
    {...},
    {...},
     ...
    {...},
  ]
}
```
ERROR LOGS:
```
Error: Could not find properties by following path: "res"!
    at TaskExec.processAction (/home/apprunner/split.js:16:34)
    at /home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:22:58
    at new Promise (<anonymous>)
    at TaskExec.process (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/executor.js:21:5)
    at processMessageWithModule (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:285:22)
    at Sailor.doProcess (/home/apprunner/node_modules/elasticio-sailor-nodejs/lib/sailor.js:248:20)
    at doProcess.next (<anonymous>)
    at onFulfilled (/home/apprunner/node_modules/co/index.js:65:19)
    at _fulfilled (/home/apprunner/node_modules/q/q.js:834:54)
    at /home/apprunner/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/apprunner/node_modules/q/q.js:796:13)
    at /home/apprunner/node_modules/q/q.js:857:14
    at runSingle (/home/apprunner/node_modules/q/q.js:137:13)
    at flush (/home/apprunner/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by kirill-levitskiy** [comment]
Please, do not forget to fix a link to the github repo as well
https://github.com/elasticio/splitter-component/issues/34

**Comment by kirill-levitskiy** [comment]
**DoD**
**Development:**
- [x] use new logger
- [x] component should be dockerised, add: "buildType":"docker" line into component.json
- [x] sailor version is changed from 2.5.4 to 2.6.2
- [x] CHANGELOG.md is updated
**QA:**
- [ ] Smoke test is finished
- [ ] Regression testing is finished (optional)
- [ ] Support is asked to deploy to the production stage (app.elastic.io) and/or another required stage
- [ ] Component is actually deployed to the production stage (app.elastic.io) and/or another required stage
- [ ] Smoke after deploying to the production stage

**Comment by kirill-levitskiy** [comment]
@ElBabbler could you add more detailed steps? I can't reproduce the issue.

**Comment by kirill-levitskiy** [comment]
After investigation it turned out that the issue is not on the component's side.
New issue for the UI was created instead https://github.com/elasticio/elasticio/issues/3226
